# Generated by Django 4.2.5 on 2023-09-18 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post2',
            new_name='Racet',
        ),
    ]
